# setup-app.yml

---
  - hosts: webservers
    become: true
    tasks:
      - name: Upload application to server
        copy:
          src: ../index.php
          dest: /var/www/html
          mode: 0755